#!/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Firefox desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Etterna desktop='^0' state=fullscreen follow=on

# Fuzzy dmenu like thing powered by FZF
bspc rule -a \*:"Fuzzy" state=floating center=on sticky=on
